### ISSUE TITLE
Preselect module when opening DQMH scripting tools

### ISSUE THREAD

**Issue by OlivierJourdan** [PantherLAB/PantherDashboard#1]
I'd love to get the module selected in the dashboard tree to be preselected in the scripting tools like "Create Event" which you can load from the dashboard.

**Comment by joerghampel** [comment]
Similar to how the Zuehlke project provider works, right? I like that idea.

https://github.com/Zuehlke/DQMH-Project-Provider

**Comment by enoearias** [comment]
![image](https://user-images.githubusercontent.com/5545396/182962288-892a0130-956f-469d-8e78-86c992a82f42.png)
Borrowed some code from:
https://github.com/Zuehlke/DQMH-Project-Provider
Thank for creating this amazing tool!
This functionality and many others will be present in the next package release.

**Comment by OlivierJourdan** [comment]
A small comment from experience with the DQMH project provider is that the 3500 ms to wait for values is not enough on large projects / slow computers.
I would increase it to at least 30s.
