### ISSUE TITLE
Add main.vi in the tree

### ISSUE THREAD

**Issue by OlivierJourdan** [PantherLAB/PantherDashboard#2]
I think it would be good to add the module main.vi in the tree to be able to open it by a double click.

Double-click on the lvlib could also display the project window with the lvlib selected.

**Comment by enoearias** [comment]
Both functionalities are implemented, and will be available on the next vip build.

**Comment by enoearias** [comment]
Removed main.vi because Drag and Drop functionality will confuse users, this Drag and Drop will allow users to minimize Project explorer usage.
