### ISSUE TITLE
DQMH Dashboard application doesn't appear

### ISSUE THREAD

**Issue by Ajedrel** [PantherLAB/PantherDashboard#33]
When I open PantherLab Dashboard it shows me the loading animation but when it finishes the dashboard doesn't appear. If I check 
the opened windows (alt+tab) the application appears but if I clicked on it nothing happens.

**Expected behavior**
The application should be displayed 

I can't share screenshots due privacy rules

**Comment by enoearias** [comment]
Hi  @Ajedrel, Panther Dashboards records the window location and window size to maintain the same user enviroment choices on each run, I think this could be the problem.

These are the steps to delete the current Panther Dashboard configuration:
- Using Windows Explorer, go to `C:\Users\<USER>\AppData\Local\PantherDashboard\`  
- Replace <USER> with your current user name
- Delete the config.ini file
- Try again opening Panther Dashboard

After you delete that file Panther Dashboard will create that file again with default values.

Please let us know if these steps fixed your issue, if it does, I can plan somethin to fix this and it will be included on the next release of Panther Dashboard.

Thank you!
Enrique.

**Comment by Ajedrel** [comment]
The problem was fixed deleting the configuration.ini
Thanks :)

**Comment by enoearias** [comment]
The code used to set the size and position of the Panther Dashboard has been removed because when users add another temporary screen or change from a higher to a lower resolution this code causes the Panther Dashboard to sit outside the bounds of the current screen .

**Comment by enoearias** [comment]
Next Release will contain these changes.
