### ISSUE TITLE
Grammar revision

### ISSUE THREAD

**Issue by dTorres594** [PantherLAB/PantherDashboard#36]
When right-clicking on a module on the FP, one option reads "Where is registered to this module's broadcasts", it would be better to state the option as "Who is registered to this module's broadcasts" or "What modules are registered to this module's broadcasts", being the first option the more adequate to keep the style of the whole application.

**Comment by enoearias** [comment]
Instead the options provided, I've decided to use 'Find code registered to this module's broadcast'.
Thanks @dTorres594 !
