### ISSUE TITLE
Modules get deleted from FP.

### ISSUE THREAD

**Issue by dTorres594** [PantherLAB/PantherDashboard#37]
**Describe the bug**
After a project has been scanned for DQMH modules, if a new scan is selected and cancelled, all previously existing modules disappear from FP. 

**To Reproduce**
1. Scan a project for DQMH modules.
2. From FP, select 'Scan Project'.
3. Close 'Modules found in project' window.
4. Modules list appears empty.

**Expected behavior**
It would be expected to keep modules found in project when scan dialog is repeated and cancelled.

**Desktop (please complete the following information):**
 - OS:  Win10 64-bit
 - Version LV2022 32-bit with DQMH 7.0

**Comment by enoearias** [comment]
Search/Scan Engine redesigned to avoid deleting previous results when user cancel Scan Window.
