### ISSUE TITLE
Icon disposition is misleading 

### ISSUE THREAD

**Issue by dTorres594** [PantherLAB/PantherDashboard#38]
In the 'Modules Found in Project' window, the function of the columns is not clear; i.e., the dependency icon has a help text stating 'Indicates if module is under dependencies' while the Scan? checkbox reads 'Include Dependencies when Searching for Modules'. 

One might think that the module is to be scanned for events whether or not the Scan? checkbox is marked, but no dependencies of the module will be listed after the scan. In reality the checkbox indicates is the module and its events are to be listed in the FP.

A better approach would be to change the context help of the Scan? control or separate the Dependency icon form the checkbox.

![image](https://github.com/PantherLAB/PantherDashboard/assets/67644463/6096dd66-3711-4839-a3ab-5e85eb1ffc74)

**Comment by enoearias** [comment]
You are correct, this problem originated from recycling some controls from somewhere else, the tip strips were not updated and this problem has existed for a long time.

Thanks!
