### ISSUE TITLE
Splash screen and the Main Window at the Same Time

### ISSUE THREAD

**Issue by Andergongar** [PantherLAB/PantherDashboard#41]
**Is your feature request related to a problem? Please describe.**
Just to have one screen as it launches

**Describe the solution you'd like**
Change the delete the "VI FP Open" from the "Set Panel initial State"
On the "Show Panel Request Event" --> Add the "Register controls Mouse Enter" to Register the controls after the Panel is loaded
Add a "Show Panel" Request to the Launcher after the Error Merge after the Splash Screen

**Describe alternatives you've considered**
Did something in my fork, but i'm using another LV version

**Additional context**
Just to have one screen

**Comment by enoearias** [comment]
Implemented, ready for the next release.
