### ISSUE TITLE
Another button to Scan the current project without the need of the dialog box

### ISSUE THREAD

**Issue by Andergongar** [PantherLAB/PantherDashboard#42]
**Is your feature request related to a problem? Please describe.**
No related to a problem, but good to have

**Describe the solution you'd like**
Add an argument to the "Scan DQMH Modules" with "All" option
Add an Value Change Event to the "Scan DQMH Modules" to trigger the scanning if the Flag is true

**Describe alternatives you've considered**

**Additional context**
a repetitive action i did a lot so i added a button

**Comment by enoearias** [comment]
Implemented, ready for the next build.
