### ISSUE TITLE
Export modules and their events to CSV file

### ISSUE THREAD

**Issue by pfoneill** [PantherLAB/PantherDashboard#45]
**Is your feature request related to a problem? Please describe.**
After scanning my DQMH project I would like to export the results to a CSV file for further analysis.

**Describe the solution you'd like**
A button that appears and allows the user to export results to file.

**Describe alternatives you've considered**
Using the DQMH Scripting API to perform a similar operation.
Using the ASCIIDOC toolkit to generate documentation - documentation is not easily editable afterwards.

**Additional context**
In projects with a lot of DQMH modules it would be nice to be able to export a module specification for auditing and for updating interfaces.
![image](https://github.com/PantherLAB/PantherDashboard/assets/19856136/eb1ce800-101c-4259-bf10-ed8a7e10a6a9)

**Comment by enoearias** [comment]
Hi @pfoneill could you please describe what do you mean with module Specification?, do you mean requests, broadcasts list?, please help me understand your use case.
The button to export on a csv file I totally get it, great Idea.
Thank you for your support on buy me a coffe, very much appreciated!.

**Comment by pfoneill** [comment]
Hi @enoearias!
Yes I think initially just a list of requests and broadcasts would be nice. I implemented a very quick solution and managed to requests and broadcasts list in the following format:
```.csv
,Corner Pane.lvlib,Request,Show Panel
,Corner Pane.lvlib,Request,Stop Module
,Corner Pane.lvlib,Request and Wait for Reply
,Corner Pane.lvlib,Request and Wait for Reply,Change Active Objective UI
,Corner Pane.lvlib,Request and Wait for Reply,Refresh Module Data
,Corner Pane.lvlib,Request and Wait for Reply,Reinitialize
,Corner Pane.lvlib,Request and Wait for Reply,Set or Reset Pending Corners
,Corner Pane.lvlib,Request and Wait for Reply,Update Nearest Corner
,Experiment Pane.lvlib
,Experiment Pane.lvlib,Broadcast
,Experiment Pane.lvlib,Broadcast,Error Reported
,Experiment Pane.lvlib,Broadcast,Experiment Confirmed
,Experiment Pane.lvlib,Broadcast,Module Did Init
,Experiment Pane.lvlib,Broadcast,Module Did Stop
,Experiment Pane.lvlib,Broadcast,Status Updated
,Experiment Pane.lvlib,Broadcast,Update Module Execution Status
,Experiment Pane.lvlib,Public API
,Experiment Pane.lvlib,Public API,Null Broadcast Events--constant
,Experiment Pane.lvlib,Public API,Obtain Broadcast Events for Registration
,Experiment Pane.lvlib,Public API,Start Module
,Experiment Pane.lvlib,Public API,Synchronize Module Events
```

**Comment by pfoneill** [comment]
Another idea I had was to have some form of caching for the Panther DQMH tool. My project is very large and it takes quite a while to scan the entire project. Rather than scanning it every time it would be nice to scan once and persist the results somewhere (rather than having to scan every time).
(this warrants a separate issue - I'll create one).

**Comment by enoearias** [comment]
Implemented on Panther Dashboard V6
https://www.vipm.io/package/pantherlab_lib_panther_dashboard/
