### ISSUE TITLE
Init screen issue

### ISSUE THREAD

**Issue by dTorres594** [PantherLAB/PantherDashboard#52]
**Describe the bug**
On Init Screen, the Scan Project works only when both Project and Target have been selected. The warning dialog reads "Select Project and/or Target".

**To Reproduce**
1. Open a DQMH Project
2. Init Panther Dashboard
3. Click on the project under the Project list and click on Scan Project.
4. The warning dialog appears.

Alternative:
1. Open a DQMH Project
2. Init Panther Dashboard
3. Click on the target under the Target list and click on Scan Project.
4. The warning dialog appears.

**Expected behavior**
As the warning dialog states that the selection could be either project or target (or both), one would expect to successfuly scan a project by selecting either one of then. If the desired behavior is to select both, modify warning dialog to the following "Select Project and Target"; if the desired behavior is for the Scan Project control to work with either selection, modify program logic to fulfill this behavior.

**Screenshots**
No selection:
![image](https://github.com/user-attachments/assets/88e9d0e3-8f7b-4162-bf2b-f9efc2fa1808)

Select only project:
![image](https://github.com/user-attachments/assets/2da8ae3b-dedd-4a16-9a67-de7d7ebee91d)

Select only target:
![image](https://github.com/user-attachments/assets/f578c8a9-043b-4a99-9f88-5a5a09643f38)

In all three cases of failure, it is evident that the PROJECT::TARGET route is ill formed. It would be expected if no selection is made.

**Desktop (please complete the following information):**
 - OS: Win10 Pro 22H2
 - LabVIEW 2020 20.0.1f1 (32-bit)
 - DQMH 7.0.1.1316

**Additional context**
The bug was seen from a DQMH project with three modules. After selecting both Project and Target, the Scan Project control works as expected.

**Comment by enoearias** [comment]
Thank you @dTorres594, issue has been addressed, it will be included on Release 6.3.7.38
