### ISSUE TITLE
About dialog unexpected behavior

### ISSUE THREAD

**Issue by dTorres594** [PantherLAB/PantherDashboard#53]
**Describe the bug**
Inside the "About Panther Dashboard" dialog, the Website documentation does not work properly when clicking on the WWW icon, only when clicking in any other part of the control.

**To Reproduce**
1. From the Main Panther Dashboard window, click on "About..."
2. Click on 'Website documentation' icon.
3. The window remains idle and no web browser is called.

**Expected behavior**
Open the intended www when clicking anywhere on the control.

**Screenshots**
![image](https://github.com/user-attachments/assets/9cd28e1e-c6db-40c4-8dc4-2735db15b10d)

**Desktop (please complete the following information):**
 - OS: Win10 Pro 2H22
 - LabVIEW 2020 20.0.1f1 (32-bit)
 - DQMH 7.0.1.1316

**Additional context**
This is a known issue when adding graphics to controls in LabVIEW. This issue might be ignored due to it not affecting the general workflow of the tool.

**Comment by enoearias** [comment]
I've implemented a temporary solution by sending the icon to the back of the button. I understand that this isn't the most elegant approach, but it should function effectively. We're fortunate to have the support of two businesses and one individual who are interested in contributing to the UI design. I'll close this issue, confident that we'll be able to address it more comprehensively in the future
